### ISSUE TITLE
como salva o boletoem pdf e segunda via do boleto

### ISSUE THREAD

**Issue by marcelowu** [santanamic/woo-cielo-boleto#2]

**Comment by santanamic** [comment]
When finalizing a purchase order an email is sent to the buyer, through it you can reimprir the boleto.

By clicking the "print" button you can select PDF as output. This works in chrome,  chrome for anroid and chrome for IOS.

Try you https://transactionsandbox.pagador.com.br/post/pagador/reenvia.asp/befde699-934e-4aca-981b-c6fdb2cf7331

OBS: Access the order menu to retrieve the Boleto.

**Comment by marcelowu** [comment]
obrigado pela dica
